name: Python Workflow

on:
  push:
    branches:
      - master  # Or specify the branch you want to trigger the workflow on
  workflow_run:
    workflows: ["Python Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Stop old workflow
      if: github.event_name == 'push'
      run: |
        echo "Stopping previous workflow..."
        curl \
          -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/cancel"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Specify the Python version you want to use

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt  # Replace with the correct command for your project

    - name: Run Python script
      run: python main.py  # Replace with the name of your Python script
